main: com.ar.askgaming.universalnotifier.UniversalNotifier
name: UniversalNotifier
version: 1.0
author: AskGaming
description: UniversalNotifier
soft-depend: [HappyHour, Warzone]
api-version: 1.21
commands:
  universalnotifier:
    description: UniversalNotifier
    usage: /universalnotifier
    permission: universalnotifier.use
    aliases:
    - un
    - notifier
  linkdicord:
    description: Link your discord account with your minecraft account
    usage: /linkdiscord <discord_id>
    permission: universalnotifier.linkdiscord
  report:
    description: Report a player
    usage: /report <message>
    permission: universalnotifier.report